#!/usr/bin/python -u
#
# CS3700, Spring 2015
# Project 2 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json     

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

MSG_SIZE = 1500
TIMEOUT = 30
DATA_SIZE = 500

#keep track of most recent sequence number

packets_received = {}

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
UDP_PORT = int(sys.argv[1])

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))

current_sequence = 0

# Now listen for packets
while True:
  result = sock.recvfrom(MSG_SIZE)

  # If nothing is ready, we hit the timeout
  if result:
    (data, addr) = result

    try:
      decoded = json.loads(data)

      # If the EOF flag is set, exit
      if (decoded['eof']):
        packet_keys = packets_received.keys()
        packet_keys.sort()
        for sequence_key in packet_keys:
            sys.stdout.write(packets_received[sequence_key])
            log(str(packets_received[sequence_key]))
        log("[completed]")
        sys.exit(0)

      # If there is data, we accept it and print it out
      if (decoded['data']):
        sequence = decoded['sequence']
        log("RECEIVED SEQUENCE: " + str(decoded['sequence']))
        if sequence == current_sequence:
          msg = json.dumps({"ack": sequence + len(decoded['data'])})
          current_sequence = sequence + len(decoded['data'])
        
          if sequence not in packets_received:
            packets_received[sequence] = decoded['data']
            # You will need to do much more here
            log("RECV [recv data] " + str(decoded['sequence']) + " (" + str(len(decoded['data'])) + ") ACCEPTED (in-order)")
        
        

        

      log("RECV ABOUT TO SEND " + msg)
      # Send back an ack to the sender
      if sock.sendto(msg, addr) < len(msg):
        log("[error] unable to fully send packet")

    except (ValueError, KeyError, TypeError) as e:
      log("RECV: [recv corrupt packet]")
      raise e
  else:
    log("[error] timeout")
    sys.exit(-1)
