#!/usr/bin/env python3

import sys, socket, select, time, json, random

# Your ID number
my_id = sys.argv[1]

# The ID numbers of all the other replicas
replica_ids = sys.argv[2:]

# Connect to the network. All messages to/from other replicas and clients will
# occur over this socket
sock = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
sock.connect(my_id)

############################# PERSISTENT STATE ON ALL SERVERS
currentTerm = 0
votedFor = None
log=[{'term': 0, 'command': 'remain follower'}]

############################# VOLATILE STATE ON ALL SERVERS
commitIndex = 0
lastApplied = 0

############################# VOLATILE STATE ON LEADERS
nextIndex = 0
matchIndex = 0

############################# OTHER IMPORTANT VARIABLES
thisRole = "follower"
numberOfMachines = len(sys.argv) - 1 # TODO THIS ISNT USED
electionTimeout = get_random_timeout() # TODO THIS ISNT USED
lastEvent = time.time() # TODO THIS ISNT USED

############################# SEND MESSAGE METHODS
def send_msg(msg):
	# SENDS A MESSAGE TO THE DST OF THE MESSAGE GIVEN
	sock.send(json.dumps(msg))

def send_to_all(msg):
	# SENDS A MESSAGE TO ALL DSTs IN REPLICA_IDS
	for id in replica_ids:
		msg['dst'] = id
		sock.send(json.dumps(msg))	


############################# REQUEST VOTE RPC METHODS
def request_vote_rpc(term, candidateId, lastLogIndex, lastLogTerm):
	global currentTerm
	if term < currentTerm:
		msg = {'src': my_id, 'dst': candidateId, 'type': 'RequestVoteResponse', 'data': False}
		send_msg(msg)
		return
	if votedFor == None or votedFor == candidateId:
		#grant vote
		votedFor = candidateId
		msg = {'src': my_id, 'dst': candidateId, 'type': 'RequestVoteResponse', 'data': True}
		send_msg(msg)
		return

############################# APPEND ENTRIES RPC METHODS
def append_entries_rpc(term, leaderId, prevLogIndex, prevLogTerm, entries, leaderCommit):
	global log, my_id
	if term < currentTerm or log[prevLogIndex] != prevLogTerm:
		msg = {'src': my_id, 'dst': candidateId, 'type': 'AppendEntriesResponse', 'success': False}
		send_msg(msg)
		return
	
	if log[prevLogIndex] == prevLogTerm:
		msg = {'src': my_id, 'dst': candidateId, 'type': 'AppendEntriesResponse', 'success': True}
	
	if len(entries) == 0:
		log = []

	for i in range(len(log)):
		this_entry = log[i]
		if i < len(entries):
			that_entry = entries[i]

			if this_entry['term'] != that_entry['term']:
				log = log[:i]
				log.append(entries[i:])
				break
		else: 
			break
	if(leaderCommit > commitIndex):
		commitIndex = min(leaderCommit, len(log)-1)

############################# STATE TRANSITION METHODS
def begin_election():
	global votedFor, currentTerm, thisRole
	#Increment current term
	currentTerm += 1
	#Change role to candidate
	thisRole = "candidate"
	#issues request vote to each of other servers
	votedFor = my_id
	data = {
		'term': currentTerm,
		'candidateId': my_id,
		'lastLogIndex': len(log) -1,
		'lastLogTerm': log[len(log)-1]['term']
	}
	msg = {'src': my_id, 'dst': candidateId, 'type': 'RequestVote', 'data': data}
	send_to_all(msg)
	print(str(msg))

def make_self_leader():
	global thisRole, leader, received_votes

	thisRole = "leader"
	leader = my_id
	received_votes = {}

	data = {
		'term': currentTerm,
		'leaderId': my_id,
		'prevLogIndex': len(log) -1,
		'prevLogTerm': log[len(log)-1]['term'],
		'entries': [],
		'leaderCommit': "TODO"
	}
	msg = {'src': my_id, 'dst': candidateId, 'type': 'AppendEntries', 'data': data}
	send_to_all(msg)

########## UTILITY METHODS
def log_is_current(lastTerm, lastIndex):
	global log
	this_last_term = log[-1]['term']
	if this_last_term < lastTerm:
		return True
	elif this_last_term > lastTerm:
		return False
	else:
		return len(log) -1 <= lastIndex

def add_headers(msg, dst, _type):
	global my_id, leader
	msg['dst'] = dst
	msg['type'] = _type


def get_random_timeout():
	#Return value between 150 and 300 ms
	return random.uniform(150,300)

############################# HANDLE RECEIVED MESSAGE METHODS
def handle_request_vote(msg):
	request_vote_rpc(msg['data']['term'], msg['data']['candidateId'], msg['data']['lastLogIndex'], msg['data']['lastLogTerm'])
	
received_votes = {}
def handle_request_vote_response(msg):
	global thisRole
	if thisRole == "candidate":
		if msg['data'] == True:
			received_votes.append(msg['src'])
			if len(received_votes) > len(replica_ids)/2.0:
				make_self_leader()
	



############################# MAIN LOOP
while True:
	ready = select.select([sock], [], [], 0.1)[0]
	
	if sock in ready:
		msg_raw = sock.recv(32768)
		
		if len(msg_raw) == 0: continue
		msg = json.loads(msg_raw)
		
		# For now, ignore get() and put() from clients
		if msg['type'] in ['get', 'put']:
			msg = {'src': my_id, 'dst': msg['src'], 'type': 'fail'}
			send_to_all(msg)
		
		# Handle noop messages. This may be removed from your final implementation
		elif msg['type'] == 'noop':
			print(msg['dst'] + ' received a NOOP from ' + msg['src'])
		
		elif msg['type'] == "RequestVote":
			handle_request_vote(msg)

		elif msg['type'] == "RequestVoteResponse":
			handle_request_vote_response(msg)

	clock = time.time()

	if clock-last > 2:
		# Send a no-op message to a random peer every two seconds, just for fun
		# You definitely want to remove this from your implementation
		msg = {'src': my_id, 'dst': random.choice(replica_ids), 'leader': 'FFFF', 'type': 'noop'}
		sock.send(json.dumps(msg))
		print(msg['src'] + ' sending a NOOP to ' + msg['dst'])
		last = clock
